[package]
name = "adventofcode-2020-rust"
version = "0.1.0"
authors = ["Andrew Marshall <amarshall@etsy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
